---
title: 'Class 6: R Functions'
author: "Enrique Sandoval"
date: "4/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### About
This is my **class 6** R markdown document with my *code* and notes for the day.

```{r}
plot(1:10, type="l", col= "blue")
```

```{r}
read.table("test1.txt", header= TRUE, sep= ",")
```

```{r}
read.table("test2.txt", header= TRUE, sep="$")
```

```{r}
read.table("test3.txt", header= FALSE, sep= "")
```


## Functions

Our first class example:

```{r}
add <- function(x, y=1) {
  #The body!!
  x+y
}
```

```{r}
add(10)
```

```{r}
add(10, y=10)
```

```{r}
add( c(1,2,3))
add( c(1,2,3), 4)
```

```{r}
#add(x=1, y= "2")
```

### Another example
```{r}
rescale <- function(x) {
rng <-range(x)
(x - rng[1]) / (rng[2] - rng[1])
}
```

```{r}
rescale(1:10)
```


```{r}
#how would you get it work here
rescale(c(1,2,NA,3,10))
```
```{r}
rescale2 <- function(x, na.rm= TRUE) {
rng <-range(x, na.rm= TRUE)
(x - rng[1]) / (rng[2] - rng[1])
}
```

```{r}
rescale2(c(1,2,NA,3,10), na.rm=FALSE )
```


```{r}
#x <- c(1,10, "string")
```



```{r}
#rescale( c(1,10,"string") )
```



```{r}
rescale3 <- function(x, na.rm=TRUE, plot=FALSE) {
rng <-range(x, na.rm=na.rm)
print("Hello")
answer <- (x - rng[1]) / (rng[2] - rng[1])
print("is it me you are looking for?")
if(plot) {
plot(answer, typ="b", lwd=4)
print("Please don't sing again...")
}
print("I can see it in ...")
return(answer)
}
```


```{r}
rescale3(c(1,3,NA,10))
```


```{r}
rescale3(c(1,3,NA,10), plot=TRUE)
```


```{r}
rescale3(c(1,3,NA,10), plot=TRUE)
```

```{r}
rescale3(c(1,3,NA,10), plot=TRUE)
```


